"""Deterministic generated-artifact drift detection."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping


@dataclass(frozen=True, slots=True)
class DriftReport:
    modified: tuple[str, ...] = ()
    missing: tuple[str, ...] = ()
    unexpected: tuple[str, ...] = ()

    @property
    def has_drift(self) -> bool:
        return bool(self.modified or self.missing or self.unexpected)


def detect_drift(expected: Mapping[str, str], actual: Mapping[str, str]) -> DriftReport:
    """Compare expected generated bytes with checked-in generated bytes."""
    expected_paths = set(expected)
    actual_paths = set(actual)
    modified = tuple(
        sorted(path for path in expected_paths & actual_paths if expected[path] != actual[path])
    )
    missing = tuple(sorted(expected_paths - actual_paths))
    unexpected = tuple(sorted(actual_paths - expected_paths))
    return DriftReport(modified=modified, missing=missing, unexpected=unexpected)
